Repository cse110-fa21-group29/cse110-fa21-group29, pull requests merged in 2021-11, with the labels that each got.

#8 Feat/7: add initial recipe json data
  source/json/recipes1.json
  source/json/recipes2.json
  source/json/recipes3.json
  source/json/recipes4.json
  source/json/recipesInfoBulk1.json
  source/json/recipesInfoBulk2.json
  source/json/recipesInfoBulk3.json
  source/json/recipesInfoBulk4.json
Labels: core

#9 specs/adrs/Recipe Cards
  specs/adrs/110821-recipe-cards
Labels: documentation

#33 feat(core): eslint and prettier set up
  .eslintrc.js
  .gitignore
  .husky/pre-commit
  .prettierignore
  .prettierrc.json
  package-lock.json
  package.json
Labels: core, testing

#35 Feat/34 GitHub actions linter
  .eslintrc.js
  .github/workflows/lint.yml
  .prettierignore
  package.json
  source/empty.js
  source/models/json/recipes1.json
  source/models/json/recipes2.json
  source/models/json/recipes3.json
  source/models/json/recipes4.json
  source/models/json/recipesInfoBulk1.json
  source/models/json/recipesInfoBulk2.json
  source/models/json/recipesInfoBulk3.json
  source/models/json/recipesInfoBulk4.json
Labels: core, testing

#28 Feat/11 implement home page
  .eslintrc.js
  .vscode/settings.json
  package-lock.json
  source/components/home-page/homepage.html
  source/components/home-page/main.js
  source/components/home-page/style.css
  source/static/home-page/demorecipe.jpg
  source/static/home-page/headerimg.jpg
Labels: enhancement, html, styling, javascript

#38 Feat/36 related issue action
  .github/workflows/close-related-issues.yml
Labels: core, testing

#40 Revert "feat(core): add close related issues action workflow (36)"
  .github/workflows/close-related-issues.yml
Labels: core, testing

#41 Initial release to test heroku
  .eslintrc.js
  .github/workflows/lint.yml
  .gitignore
  .husky/pre-commit
  .prettierignore
  .prettierrc.json
  .vscode/settings.json
  admin/meetings/110921-sprint1cont.md
  package-lock.json
  package.json
  source/components/home-page/homepage.html
  source/components/home-page/main.js
  source/components/home-page/style.css
  source/empty.js
  source/models/json/recipes1.json
  source/models/json/recipes2.json
  source/models/json/recipes3.json
  source/models/json/recipes4.json
  source/models/json/recipesInfoBulk1.json
  source/models/json/recipesInfoBulk2.json
  source/models/json/recipesInfoBulk3.json
  source/models/json/recipesInfoBulk4.json
  source/static/home-page/demorecipe.jpg
  source/static/home-page/headerimg.jpg
Labels: core, testing

#43 Feat/31 remove slick
  source/components/home-page/homepage.html
  source/components/home-page/main.js
  source/components/home-page/style.css
  source/static/home-page/red-panda.png
Labels: html, styling, javascript

#49 Feat/10 model json data
  source/models/json/parsedRecipes.json
  source/models/scripts/recipeParser.py
Labels: enhancement, core

#51 Feat/42 - Test firebase hosting
  .firebaserc
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  firebase.json
  package-lock.json
Labels: core

#53 feat(hosting): add dev environment for hosting (42b)
  .firebaserc
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-main.yml
  .github/workflows/lint.yml
  .github/workflows/pull-request-dev.yml
  .github/workflows/pull-request-main.yml
Labels: core

#56 fix(core): update github workflows (42c)
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-main.yml
  .github/workflows/pull-request-dev.yml
  .github/workflows/pull-request-main.yml
Labels: core

#58 Releases/test 1
  .firebaserc
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-main.yml
  .github/workflows/lint.yml
  .github/workflows/pull-request-dev.yml
  .github/workflows/pull-request-main.yml
  README.md
Labels: core

#61 feat(contribute): add a recipe grid
  source/components/home-page/home-page.css
  source/components/home-page/home-page.html
  source/components/home-page/home-page.js
Labels: html, styling

#68 Feat/50 add protein healthy categories
  source/models/json/parsedRecipes.json
  source/models/scripts/recipeParser.py
Labels: enhancement, core

#108 Feat/107 hide arrow
  source/components/home-page/home-page.css
  source/components/home-page/home-page.js
Labels: bug, html, styling

#109 Feat/101 search page
  source/components/recipe-search/recipe-search.css
  source/components/recipe-search/recipe-search.html
  source/components/recipe-search/recipe-search.js
  source/core/routing/router.js
  source/index.html
Labels: html, styling

#110 Feat/64 hands free page
  source/components/hands-free/hands-free.css
  source/components/hands-free/hands-free.html
  source/components/hands-free/hands-free.js
  source/core/routing/router.js
  source/index.html
Labels: html, styling

#115 feat(navbar): help to developers
  source/components/common/nav-bar/common-nav-bar.css
  source/components/common/nav-bar/common-nav-bar.html
Labels: html, styling

#103 Feat/102 Add JSDocs to router JS
  source/core/routing/router.js
Labels: documentation, javascript

#127 fix(router): update docs
  source/core/routing/router.js
Labels: bug, core

#128 fix(router): fix state when navigating from url
  source/core/routing/router.js
Labels: bug, core

#130 feat(core): install commitlint
  .husky/commit-msg
  commitlint.config.js
  package-lock.json
  package.json
Labels: core, testing

#132 Feat/111 Development Docs
  admin/misc/developer-workflow.md
  specs/documentation/development/README.md
  specs/documentation/development/branching-and-committing.md
  specs/documentation/development/component-structure.md
  specs/documentation/development/development-folder-structure.md
  specs/documentation/development/development-workflow.md
  specs/documentation/development/firebase-explanation.md
  specs/documentation/development/local-environment-setup.md
  specs/documentation/development/screenshots/commitlint-fail.png
  specs/documentation/development/screenshots/eslint-prettier-fail.png
  specs/documentation/development/screenshots/eslint-prettier-success.png
  specs/documentation/empty.md
Labels: documentation, core

#133 docs(dev): add database function explainations
  specs/documentation/development/README.md
  specs/documentation/development/firebase-explanation.md
Labels: documentation, core

#124 Feat/120 add jest pipeline
  .eslintrc.js
  .github/workflows/pull-request-dev.yml
  .github/workflows/pull-request-main.yml
  package-lock.json
  package.json
  source/core/routing/router.js
  unit-tests/router.test.js
Labels: enhancement, core

#135 Feat/121 add jsdocs pipeline
  .github/workflows/pull-request-dev.yml
  .github/workflows/pull-request-main.yml
  specs/documentation/jsdocs/docHomepage.md
  specs/documentation/jsdocs/empty.md
Labels: enhancement, core

#141 Feat/44 add crud functionality
  .gitignore
  source/components/home-page/home-page.css
  source/components/home-page/home-page.html
  source/components/home-page/home-page.js
  source/components/recipe-contribute/recipe-contribute.html
  source/components/recipe-contribute/recipe-contribute.js
  source/components/recipe-details/recipe-details.html
  source/components/recipe-details/recipe-details.js
  source/config.json
  source/core/database/database.js
  source/core/routing/router.js
  source/index.html
  source/models/json/parsedRecipes.json
Labels: enhancement, core, javascript

#145 feat(details): add edit button that routes to recipe-contribute-edit
  source/components/recipe-details/recipe-details.html
  source/components/recipe-details/recipe-details.js
Labels: enhancement, core, javascript

#149 feat(recipe-card): extract recipe card into its own component
  source/components/common/recipe-card/common-recipe-card.css
  source/components/common/recipe-card/common-recipe-card.html
  source/components/common/recipe-card/common-recipe-card.js
  source/components/home-page/home-page.css
  source/components/home-page/home-page.html
  source/components/home-page/home-page.js
  source/index.html
Labels: enhancement, javascript, component

#150 feat(search): draft
  source/components/common/nav-bar/common-nav-bar.html
  source/components/recipe-search/recipe-search.css
  source/components/recipe-search/recipe-search.html
  source/components/recipe-search/recipe-search.js
  source/core/routing/router.js
  source/static/common/close-icon.png
  source/static/common/filter-icon.png
  source/static/common/search-icon.png
Labels: html, styling

#182 fix(router): remove get params from url before matching to route pattern
  source/core/routing/router.js
Labels: bug, core, routing

#183 Feat/119 navbar hamburger
  source/components/common/nav-bar/common-nav-bar.css
  source/components/common/nav-bar/common-nav-bar.html
  source/components/home-page/home-page.css
  source/components/home-page/home-page.html
  source/components/meal-planner/meal-planner.css
  source/components/recipe-contribute/recipe-contribute.css
Labels: html, styling

#185 refactor(component): add generic yummy recipes component (164)
  source/components/TEMPLATE/component-name.js
  source/components/about-us/about-us.js
  source/components/common/footer/common-footer.js
  source/components/common/nav-bar/common-nav-bar.js
  source/components/common/recipe-card/common-recipe-card.js
  source/components/core/yummy-recipes-component.js
  source/components/hands-free/hands-free.js
  source/components/home-page/home-page.js
  source/components/meal-planner/meal-planner.js
  source/components/recipe-contribute/recipe-contribute.js
  source/components/recipe-details/recipe-details.js
  source/components/recipe-search/recipe-search.js
  specs/documentation/development/development-folder-structure.md
Labels: enhancement, core, javascript, component

#186 feat(ui): remove default data from components (165)
  source/components/common/recipe-card/common-recipe-card.html
  source/components/recipe-details/recipe-details.html
  source/components/recipe-details/recipe-details.js
Labels: enhancement, html

#184 feat(detailpage): style and timer
  source/components/recipe-details/recipe-details.css
  source/components/recipe-details/recipe-details.html
  source/components/recipe-details/recipe-details.js
Labels: html, styling

#205 Feat/146 implement image upload
  source/components/recipe-contribute/recipe-contribute.html
  source/components/recipe-contribute/recipe-contribute.js
  source/components/recipe-details/recipe-details.js
  source/core/database/database.js
  source/core/storage/storage.js
Labels: enhancement, core, javascript, hosting

#208 feat(recipe-contribute): add form validation
  source/components/recipe-contribute/recipe-contribute.html
  source/components/recipe-contribute/recipe-contribute.js
  source/styles.css
Labels: enhancement, javascript

#209 feat(search-page): style
  source/components/recipe-search/recipe-search.css
  source/components/recipe-search/recipe-search.html
Labels: styling

#213 feat(font): add font
  source/static/font/Montserrat-Black.ttf
  source/static/font/SnellRoundhand-BlackScript.otf
  source/styles.css
Labels: styling

#212 feat(contributepage): style
  source/components/recipe-contribute/recipe-contribute.css
  source/components/recipe-contribute/recipe-contribute.html
Labels: styling
