Repository cse110-fa21-group29/cse110-fa21-group29, pull requests merged in 2021-12, with the labels that each got.

#229 Test/195 routing unit tests
  package-lock.json
  source/core/routing/router.js
  testing/unit-tests/router.test.js
  unit-tests/router.test.js
Labels: pipeline

#233 Feat/228 style
  source/components/about-us/about-us.css
  source/components/common/nav-bar/common-nav-bar.html
  source/components/common/recipe-card/common-recipe-card.css
  source/components/home-page/home-page.css
  source/components/meal-planner/meal-planner.css
  source/components/meal-planner/meal-planner.html
  source/components/meal-planner/meal-planner.js
  source/components/recipe-contribute/recipe-contribute.css
  source/components/recipe-search/recipe-search.css
Labels: styling

#234 Test/220 routing e2e testing
  .github/workflows/pull-request-dev.yml
  .github/workflows/pull-request-main.yml
  package-lock.json
  package.json
  source/core/routing/router.js
  testing/e2e-tests/router.test.js
  testing/unit-tests/router.test.js
Labels: pipeline

#239 Fix/237 fix module exports
  source/core/routing/router.js
  testing/e2e-tests/router.test.js
Labels: bug, pipeline, -PRIORITY: CRITICAL

#236 Feat/228b style
  source/components/hands-free/hands-free.css
  source/components/hands-free/hands-free.html
  source/components/meal-planner/meal-planner.html
  source/components/recipe-details/recipe-details.css
  source/components/recipe-details/recipe-details.html
Labels: styling

#241 feat(recipes): re-parsed recipes to make steps a list.
  source/models/json/newParsedRecipes.json
  source/models/scripts/recipeParser.py
Labels: core, database

#240 Fix/227 broken recipe cards
  source/components/home-page/home-page.js
Labels: bug, core, javascript, database

#244 Feat/224 recipe videos
  source/components/recipe-contribute/recipe-contribute.js
  source/components/recipe-details/recipe-details.css
  source/components/recipe-details/recipe-details.html
  source/components/recipe-details/recipe-details.js
Labels: enhancement, html, javascript, database

#246 feat(recipe-search): search submit button (230)
  source/components/common/nav-bar/common-nav-bar.html
  source/components/common/nav-bar/common-nav-bar.js
  source/components/recipe-search/recipe-search.css
  source/components/recipe-search/recipe-search.js
  source/core/routing/router.js
Labels: enhancement, javascript

#247 fix(recipe-contribute): add step and min to number fields (225)
  source/components/recipe-contribute/recipe-contribute.html
Labels: bug, html

#248 feat(nav-bar): add category links to search (217)
  source/components/common/nav-bar/common-nav-bar.html
Labels: enhancement, html

#253 Feat/252 update new icon
  source/static/common/close-icon.png
  source/static/common/filter-icon.png
Labels: design

#251 Feat/176 write about us description
  package-lock.json
  source/components/about-us/about-us.css
  source/components/about-us/about-us.html
  source/static/about-us/avery.jpg
  source/static/about-us/baha.jpg
  source/static/about-us/edbert.JPG
  source/static/about-us/enzo.jpg
  source/static/about-us/fangcheng.jpg
  source/static/about-us/haonan.JPG
  source/static/about-us/jeffrey.jpg
  source/static/about-us/jiayi.jpg
  source/static/about-us/justin.jpg
  source/static/about-us/tri.JPG
  source/static/about-us/zhuoran.jpg
Labels: enhancement, html, styling

#255 fix(about-us): fix broken team member picture (254)
  source/components/about-us/about-us.html
Labels: bug, html

#256 Feat/170 meal planner pt 1
  source/components/meal-planner/meal-planner.html
  source/components/meal-planner/meal-planner.js
  source/core/database/database.js
Labels: enhancement, javascript

#259 fix(nav-bar): remove navbar link to search
  source/components/common/nav-bar/common-nav-bar.html
Labels: bug, html

#264 fix(recipe-details): route to home page if recipe is undefined (261)
  source/components/hands-free/hands-free.js
  source/components/recipe-contribute/recipe-contribute.js
  source/components/recipe-details/recipe-details.js
  source/core/routing/router.js
  testing/unit-tests/router.test.js
Labels: bug, javascript

#266 feat(core): upload favicon image (265)
  source/favicon-16x16.png
  source/favicon-32x32.png
  source/favicon.ico
  source/index.html
  source/safari-pinned-tab.svg
Labels: enhancement, styling

#268 feat(core): fix node version for jsdocs
  .github/workflows/pull-request-dev.yml
  .github/workflows/pull-request-main.yml
Labels: bug, core

#270 Feat/262 meal planner style
  source/components/common/recipe-card/common-recipe-card.css
  source/components/home-page/home-page.css
  source/components/home-page/home-page.html
  source/components/meal-planner/meal-planner-recipe-card/meal-planner-recipe-card.css
  source/components/meal-planner/meal-planner-recipe-card/meal-planner-recipe-card.html
  source/components/meal-planner/meal-planner-recipe-card/meal-planner-recipe-card.js
  source/components/meal-planner/meal-planner.css
  source/components/meal-planner/meal-planner.html
  source/components/meal-planner/meal-planner.js
Labels: styling

#275 fix(data): add highProtein and healthy categories
  source/models/json/newParsedRecipes.json
  source/models/scripts/recipeParser.py
Labels: database, - PRIORITY: HIGH

#271 fix(recipes): new step structure and ignoring blank lines
  source/components/recipe-contribute/recipe-contribute.js
  source/components/recipe-details/recipe-details.js
  source/models/json/newParsedRecipes.json
Labels: bug, core, javascript, database

#278 Test/273 more e2e tests routing
  testing/e2e-tests/router.test.js
Labels: pipeline, - PRIORITY: HIGH

#281 Fix/279 core resolve codacy issues
  source/components/hands-free/hands-free.css
  source/components/meal-planner/meal-planner.css
  source/components/recipe-contribute/recipe-contribute.js
  source/components/recipe-details/recipe-details.js
Labels: core, - PRIORITY: CRITICAL

#277 Feat/272 hands free functionality
  source/components/hands-free/hands-free.css
  source/components/hands-free/hands-free.html
  source/components/hands-free/hands-free.js
Labels: enhancement, javascript, database

#284 fix(core): add base to each parseInt
  source/components/common/recipe-card/common-recipe-card.js
  source/components/hands-free/hands-free.js
  source/components/recipe-details/recipe-details.js
  source/core/routing/router.js
Labels: core, - PRIORITY: HIGH

#282 Feat/249 timer
  source/components/hands-free/hands-free.css
  source/components/hands-free/hands-free.html
  source/components/hands-free/hands-free.js
  source/static/hands-free/timer-done-noise.mp3
Labels: enhancement, html, javascript

#286 Fix/core: resolve codacy issues
  source/core/database/database.js
  source/core/routing/router.js
Labels: core, - PRIORITY: HIGH

#285 Feat/168 randomized recipes
  source/components/home-page/home-page.js
Labels: enhancement, javascript, database

#295 fix(home-page): fix undefined recipe index check
  source/components/home-page/home-page.js
Labels: bug, core, javascript, database, component

#296 Feat/258 about us styling fix
  source/components/about-us/about-us.css
  source/static/font/Sofia-Regular.ttf
  source/styles.css
Labels: styling, design, - PRIORITY: MEDIUM

#294 Feat/249 add timer to recipe details
  source/components/hands-free/hands-free.js
  source/components/recipe-details/recipe-details.css
  source/components/recipe-details/recipe-details.html
  source/components/recipe-details/recipe-details.js
Labels: html, javascript

#297 Test/269 e2e test database
  testing/e2e-tests/database.test.js
Labels: pipeline, - PRIORITY: HIGH

#298 Feat/228c style
  source/components/common/nav-bar/common-nav-bar.css
  source/components/common/recipe-card/common-recipe-card.css
  source/components/home-page/home-page.css
  source/components/recipe-contribute/recipe-contribute.css
  source/components/recipe-contribute/recipe-contribute.html
  source/components/recipe-details/recipe-details.css
  source/components/recipe-details/recipe-details.html
  source/components/recipe-details/recipe-details.js
  source/components/recipe-search/recipe-search.css
Labels: styling

#289 Feat/172 pagination functionality
  README.md
  source/components/recipe-search/recipe-search.css
  source/components/recipe-search/recipe-search.html
  source/components/recipe-search/recipe-search.js
  specs/adrs/111921-recipe-json-structure.md
Labels: enhancement, design, javascript, database

#308 Feat/299 improve home page styling
  source/components/common/footer/common-footer.css
  source/components/common/footer/common-footer.html
  source/components/home-page/home-page.css
  source/components/home-page/home-page.html
  source/components/home-page/home-page.js
Labels: html, styling, - PRIORITY: CRITICAL

#310 Feat/299b home page styling
  source/components/home-page/home-page.css
  source/components/home-page/home-page.html
Labels: html, styling

#311 Fix/279 core resolve codacy issues
  source/components/home-page/home-page.js
  source/components/recipe-contribute/recipe-contribute.js
  source/components/recipe-details/recipe-details.js
  source/core/database/database.js
  source/core/routing/router.js
Labels: bug, core, - PRIORITY: HIGH

#309 Feat/300 about us styling fixx
  source/components/about-us/about-us.css
  source/components/about-us/about-us.html
  source/static/about-us/team29.jpg
Labels: html, styling, - PRIORITY: CRITICAL

#317 style(recipe-details): move video to correct place
  source/components/recipe-details/recipe-details.css
  source/components/recipe-details/recipe-details.html
  source/components/recipe-details/recipe-details.js
Labels: html, styling, - PRIORITY: CRITICAL

#322 Fix/318 meal planner firefox
  source/components/common/nav-bar/common-nav-bar.html
  source/components/meal-planner/meal-planner.js
Labels: bug, javascript, routing

#328 Fix/323 Meal Planner Routing
  source/components/meal-planner/meal-planner.js
Labels: bug, javascript, routing

#329 Feat/301 recipe details styling
  source/components/recipe-details/recipe-details.css
  source/components/recipe-details/recipe-details.html
  source/components/recipe-details/recipe-details.js
Labels: html, styling, - PRIORITY: CRITICAL

#335 Fix/334 Planner Card Loading
  source/components/meal-planner/meal-planner.css
  source/components/meal-planner/meal-planner.html
  source/components/meal-planner/meal-planner.js
Labels: enhancement, html, javascript

#315 Feat/303 timer styling
  source/components/cooking-mode/cooking-mode.css
  source/components/cooking-mode/cooking-mode.html
  source/components/cooking-mode/cooking-mode.js
  source/components/hands-free/hands-free.html
  source/components/recipe-details/recipe-details.html
  source/components/recipe-details/recipe-details.js
  source/core/routing/router.js
  source/index.html
  source/static/cooking-mode/timer-done-noise.mp3
  testing/e2e-tests/router.test.js
  testing/unit-tests/router.test.js
Labels: html, javascript, routing, - PRIORITY: CRITICAL

#330 Feat/304 search page style
  source/components/recipe-search/recipe-search.css
  source/components/recipe-search/recipe-search.html
  source/components/recipe-search/recipe-search.js
Labels: html, styling, - PRIORITY: CRITICAL

#336 Feat/307 overall font
  source/components/recipe-details/recipe-details.html
  source/index.html
  source/styles.css
Labels: html, styling, - PRIORITY: CRITICAL

#327 Feat/306 improve nav bar recipe card
  source/components/common/nav-bar/common-nav-bar.css
  source/components/common/nav-bar/common-nav-bar.html
  source/components/common/nav-bar/common-nav-bar.js
  source/components/common/recipe-card/common-recipe-card.css
Labels: core, styling, DON'T MERGE, - PRIORITY: HIGH

#338 Feat/302 recipe contribute styling
  source/components/recipe-contribute/recipe-contribute.css
  source/components/recipe-contribute/recipe-contribute.html
  source/components/recipe-details/recipe-details.css
  source/static/common/demorecipe.jpg
  testing/e2e-tests/router.test.js
Labels: html, styling, - PRIORITY: CRITICAL

#339 fix(recipe-search): begin with empty query in url search params
  source/components/recipe-search/recipe-search.js
Labels: bug, javascript, - PRIORITY: CRITICAL

#341 Feat/337 add text img
  source/components/recipe-contribute/recipe-contribute.css
  source/components/recipe-contribute/recipe-contribute.html
  source/components/recipe-contribute/recipe-contribute.js
Labels: styling

#346 fix(recipe-search): fix typo and remove unnecessary comment
  source/components/recipe-search/recipe-search.js
Labels: bug, javascript, - PRIORITY: CRITICAL

#349 style(timer): fix buttons overlapping with input
  source/components/cooking-mode/cooking-mode.css
  source/components/cooking-mode/cooking-mode.html
Labels: html, styling

#352 Feat/342 remove commented code
  source/components/common/recipe-card/common-recipe-card.css
  source/components/home-page/home-page.html
  source/components/recipe-search/recipe-search.html
Labels: core, html, styling, javascript, - PRIORITY: HIGH

#351 Feat/340 refactor router search params
  source/components/cooking-mode/cooking-mode.css
  source/components/cooking-mode/cooking-mode.html
  source/components/cooking-mode/cooking-mode.js
  source/components/core/yummy-recipes-component.js
  source/components/meal-planner/meal-planner.js
  source/components/recipe-details/recipe-details.html
  source/components/recipe-details/recipe-details.js
  source/components/recipe-search/recipe-search.js
  source/core/routing/router.js
Labels: bug, core, javascript, routing, - PRIORITY: CRITICAL

#356 fix(jsdocs): add a few comments for functions and classes without one
  source/components/TEMPLATE/component-name.js
  source/components/common/footer/common-footer.js
  source/components/common/nav-bar/common-nav-bar.js
  source/components/common/recipe-card/common-recipe-card.js
  source/components/home-page/home-page.js
  source/components/recipe-search/recipe-search.js
Labels: - PRIORITY: MEDIUM

#347 feat(about-us): img change
  source/components/about-us/about-us.css
  source/components/about-us/about-us.html
  source/components/about-us/about-us.js
  source/static/about-us/triscouch.jpg
Labels: javascript

#360 feat(recipe-contribute): adjust margin and add box shadow to inputs a…
  source/components/recipe-contribute/recipe-contribute.css
Labels: styling, - PRIORITY: MEDIUM

#358 Feat/350 timer styling formatting
  source/components/cooking-mode/cooking-mode.css
  source/components/cooking-mode/cooking-mode.html
  source/components/cooking-mode/cooking-mode.js
  source/components/recipe-details/recipe-details.html
Labels: core, styling, - PRIORITY: HIGH
